# Generated by Django 6.1.1 on 2026-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_accordionitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
